#!/bin/bash
REMOTE=$1
if [[ $REMOTE == "" ]]; then
  echo "Please provide a remote e.g repush master"
  exit 1
fi
echo "Using remote $REMOTE"
function echo_green()
{
  tput setaf 2
    echo $1
    tput sgr0
}
function echo_same_line()
{
  echo -ne "Pending \033[0k\r"
}
echo_green "Attempting repush.."
while true
do
wget -q --tries=10 --timeout=20 --spider http://google.com
if [[ $? -eq 0 ]]; then
echo_green "Online..."
echo_green "Pushing..."
`git push origin $REMOTE`
exit 0
else
echo_same_line
fi
done
